### PR TITLE
Extending validity of testing certificates

### PR DESCRIPTION
**Pull request by armfazh**
Extends validity of testing certificates.

### CODE REVIEW

**Comment by thibmeu** [comment]
Looks ok based on 
```
for pem_file in tests/*.pem; do
    echo "Validity of $pem_file:"
    openssl x509 -in "$pem_file" -noout -dates
    echo "----------------------------------"
done
```

Question: why not update ca.pem?

**Comment by bwesterb** [comment]
Can't we generate these on-demand so that we don't have to do this maintenance every odd year?

**Comment by Lekensteyn** [comment]
> Can't we generate these on-demand so that we don't have to do this maintenance every odd year?

Either that or use something like `-days 36500` to make certificates that are valid for 100 years. Or somehow fix the date and time that is used for verification purposes.

**Review by lukevalenta — APPROVED** [review]
I'm fine with merging as-is, and we can follow up later with the proposed changes for longer certificate lifetimes or automatic test certificate generation.

**Pull request merged**
